import { precacheAndRoute } from 'workbox-precaching';

// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('install', function(event) {
  self.skipWaiting();
});
self.addEventListener('message', (messageEvent) => {
  if (messageEvent.data === 'skipWaiting') return self.skipWaiting();
});
